version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
  redis_container:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  mongodb_data_container:
  redis_data:
